### ISSUE TITLE
Too many MongoDB connections bug

### ISSUE THREAD

**Issue by ebrensi** [ebrensi/heatflask#50]
Lately I have been getting notified from Atlas MongoDB that the number of connections is high (above 80).  I have it limited at 100.  There is no reason why that many mongoDB connections should be open.  When I look at the app logs, I am seeing the following exception repeated over and over again, as far back as I can see:

```
Sept 22 20:30:56 heatflask app/web.1 Traceback (most recent call last): 
Sept 22 20:30:56 heatflask app/web.1   File "/app/.heroku/python/lib/python2.7/site-packages/pymongo/mongo_client.py", line 1199, in _process_periodic_tasks 
Sept 22 20:30:56 heatflask app/web.1     self._topology.update_pool() 
Sept 22 20:30:56 heatflask app/web.1   File "/app/.heroku/python/lib/python2.7/site-packages/pymongo/topology.py", line 342, in update_pool 
Sept 22 20:30:56 heatflask app/web.1     server._pool.remove_stale_sockets() 
Sept 22 20:30:56 heatflask app/web.1   File "/app/.heroku/python/lib/python2.7/site-packages/pymongo/pool.py", line 789, in remove_stale_sockets 
Sept 22 20:30:56 heatflask app/web.1     sock_info = self.connect() 
Sept 22 20:30:56 heatflask app/web.1   File "/app/.heroku/python/lib/python2.7/site-packages/pymongo/pool.py", line 816, in connect 
Sept 22 20:30:56 heatflask app/web.1     DEFAULT_CODEC_OPTIONS)) 
Sept 22 20:30:56 heatflask app/web.1   File "/app/.heroku/python/lib/python2.7/site-packages/pymongo/network.py", line 108, in command 
Sept 22 20:30:56 heatflask app/web.1     response = receive_message(sock, 1, request_id) 
Sept 22 20:30:56 heatflask app/web.1   File "/app/.heroku/python/lib/python2.7/site-packages/pymongo/network.py", line 137, in receive_message 
Sept 22 20:30:56 heatflask app/web.1     header = _receive_data_on_socket(sock, 16) 
Sept 22 20:30:56 heatflask app/web.1   File "/app/.heroku/python/lib/python2.7/site-packages/pymongo/network.py", line 170, in _receive_data_on_socket 
Sept 22 20:30:56 heatflask app/web.1     raise AutoReconnect("connection closed") 
Sept 22 20:30:56 heatflask app/web.1 AutoReconnect: connection closed 
```

**Comment by ebrensi** [comment]
fixed
