### ISSUE TITLE
problem with Strava activity-id?

### ISSUE THREAD

**Issue by ebrensi** [ebrensi/heatflask#73]
Noticed this error in the logs when retrieving activity data for user 3551035

```
Traceback (most recent call last):
     File "/app/.heroku/python/lib/python2.7/site-packages/gevent/pywsgi.py", line 976, in handle_one_response
       self.run_application()
     File "/app/.heroku/python/lib/python2.7/site-packages/geventwebsocket/handler.py", line 75, in run_application
       self.run_websocket()
     File "/app/.heroku/python/lib/python2.7/site-packages/geventwebsocket/handler.py", line 52, in run_websocket
       list(self.application(self.environ, lambda s, h, e=None: []))
     File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 2463, in __call__
       return self.wsgi_app(environ, start_response)
     File "/app/.heroku/python/lib/python2.7/site-packages/flask_sockets.py", line 45, in __call__
       handler(environment, **values)
     File "/app/heatflask/routes.py", line 539, in data_socket
       for a in Activities.query(query):
     File "/app/heatflask/models.py", line 1420, in query
       for a in user.query_activities(**query):
     File "/app/heatflask/models.py", line 468, in query_activities
       update_ts=update_index_ts
     File "/app/heatflask/models.py", line 952, in query
       int(doc["_id"]) for doc in result
     File "/app/heatflask/models.py", line 952, in <genexpr>
       int(doc["_id"]) for doc in result
     File "/app/.heroku/python/lib/python2.7/site-packages/pymongo/cursor.py", line 1156, in next
       if len(self.__data) or self._refresh():
     File "/app/.heroku/python/lib/python2.7/site-packages/pymongo/cursor.py", line 1073, in _refresh
       self.__send_message(q)
     File "/app/.heroku/python/lib/python2.7/site-packages/pymongo/cursor.py", line 955, in __send_message
       address=self.__address)
     File "/app/.heroku/python/lib/python2.7/site-packages/pymongo/mongo_client.py", line 1347, in _run_operation_with_response
       exhaust=exhaust)
     File "/app/.heroku/python/lib/python2.7/site-packages/pymongo/mongo_client.py", line 1465, in _retryable_read
       return func(session, server, sock_info, slave_ok)
     File "/app/.heroku/python/lib/python2.7/site-packages/pymongo/mongo_client.py", line 1341, in _cmd
       unpack_res)
     File "/app/.heroku/python/lib/python2.7/site-packages/pymongo/server.py", line 102, in run_operation_with_response
       set_slave_okay, sock_info, use_cmd)
     File "/app/.heroku/python/lib/python2.7/site-packages/pymongo/message.py", line 336, in get_message
       ctx=sock_info.compression_context)
     File "/app/.heroku/python/lib/python2.7/site-packages/pymongo/message.py", line 704, in _op_msg
       flags, command, identifier, docs, check_keys, opts)
   OverflowError: MongoDB can only handle up to 8-byte ints
   2019-11-05T16:57:10Z {'REMOTE_PORT': '25880', 'REMOTE_ADDR': '10.5.212.115', 'HTTP_HOST': 'www.heatflask.com', (hidden keys: 42)} failed with OverflowError
```

**Comment by ebrensi** [comment]
I think this bug went away after last revision.
