### ISSUE TITLE
unauthorized access bug

### ISSUE THREAD

**Issue by ebrensi** [ebrensi/heatflask#84]
This bug has been around for a while.  Seemingly at random I get this error when a user requests the activities page or attempts to change share status.
Finally getting around to addressing this.

```
Nov 19 14:27:54 [53] [ERROR] Exception on /1380661/activities [GET]
Nov 19 14:27:54 Traceback (most recent call last):
Nov 19 14:27:54 File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
Nov 19 14:27:54 response = self.full_dispatch_request()
Nov 19 14:27:54 File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
Nov 19 14:27:54 return self.finalize_request(rv)
Nov 19 14:27:54 File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1967, in finalize_request
Nov 19 14:27:54 response = self.make_response(rv)
Nov 19 14:27:54 File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 2097, in make_response
Nov 19 14:27:54 "The view function did not return a valid response. The"
Nov 19 14:27:54 TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
Nov 19 14:29:09 at=info method=GET path="/1380661/update_info" host=www.heatflask.com request_id=f40c3a9a-262b-45ec-a9f7-b90265b248d0 fwd="66.249.64.175" dyno=web.1 connect=1ms service=752ms status=500 bytes=411 protocol=https

Nov 19 14:29:09 [53] [ERROR] Exception on /1380661/update_info [GET]
Nov 19 14:29:09 Traceback (most recent call last):
Nov 19 14:29:09 response = self.full_dispatch_request()
Nov 19 14:29:09 File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
Nov 19 14:29:09 return self.finalize_request(rv)
Nov 19 14:29:09 response = self.make_response(rv)
Nov 19 14:29:09 File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 2097, in make_response
Nov 19 14:29:09 "The view function did not return a valid response. The"
Nov 19 14:29:09 TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
```

**Comment by ebrensi** [comment]
fixed with pull https://github.com/ebrensi/heatflask/pull/85.
